export const templates = [
  {
    id: 'featured-property',
    number: '01',
    title: 'Propiedad destacada',
    description: 'Presenta una propiedad específica y convierte el interés en visitas.',
    objective: 'Presentar una propiedad específica y conseguir solicitudes de visita calificadas.',
    cta: 'Agendar visita',
    detailLabel: 'Cuéntanos sobre la propiedad',
    detailPlaceholder: 'Ej. Casa de 3 recámaras en Zona Río, terraza, estudio y vista panorámica…',
    detailHint: 'Incluye únicamente datos reales: tipo, recámaras, amenidades, precio si deseas mostrarlo y atributos de la zona.',
    journey: 'Anuncio o recomendación → impacto visual → detalles y estilo de vida → confianza → solicitud de visita.',
    sections: [
      'Hero con la propiedad, propuesta concreta y CTA de visita visible',
      'Galería editorial preparada para fotografías reales, plano y tour virtual si existen',
      'Resumen escaneable de características y amenidades verificadas',
      'Narrativa de espacios, estilo de vida y ventajas de la ubicación',
      'Proceso para agendar y bloque de preguntas frecuentes',
      'CTA final con el mismo mensaje principal',
    ],
    formFields: 'nombre, medio de contacto, horario preferido y situación de compra opcional',
  },
  {
    id: 'sell-property',
    number: '02',
    title: 'Quiero vender mi propiedad',
    description: 'Capta propietarios que quieren conocer el valor y potencial de su inmueble.',
    objective: 'Captar propietarios interesados en vender y convertirlos en solicitudes de valoración.',
    cta: 'Solicitar valoración',
    detailLabel: 'Describe el servicio de valoración',
    detailPlaceholder: 'Ej. Análisis comparativo, estrategia de precio, fotografía profesional y difusión en portales…',
    detailHint: 'Explica tu método real, cobertura y qué recibe el propietario; evita prometer un precio automático.',
    journey: 'Inquietud por vender → claridad sobre el valor → método y alcance → confianza local → solicitud de valoración.',
    sections: [
      'Hero centrado en obtener una valoración clara, sin promesas infladas',
      'Qué incluye el análisis y cómo ayuda a tomar una decisión',
      'Metodología de precio, promoción y filtrado de compradores',
      'Conocimiento de la zona y evidencia real disponible',
      'Proceso de venta explicado en pasos simples',
      'Formulario breve de propiedad y CTA para solicitar valoración',
    ],
    formFields: 'zona o colonia, tipo de inmueble, estado general, plazo estimado y datos de contacto',
  },
  {
    id: 'find-property',
    number: '03',
    title: 'Estoy buscando propiedad',
    description: 'Conoce las necesidades del comprador antes de iniciar la conversación.',
    objective: 'Calificar compradores y ayudarles a recibir una selección de propiedades relevantes.',
    cta: 'Recibir opciones',
    detailLabel: '¿Qué tipo de búsqueda quieres atender?',
    detailPlaceholder: 'Ej. Primera vivienda entre $3 y $5 MDP, 2 o 3 recámaras, cerca de escuelas y con crédito…',
    detailHint: 'Describe zonas, rangos, tipos de propiedad o necesidades frecuentes de tus compradores.',
    journey: 'Necesidad de encontrar propiedad → promesa de selección relevante → preferencias → proceso → contacto con asesor.',
    sections: [
      'Hero con una promesa específica de búsqueda acompañada',
      'Beneficios de una selección curada frente a buscar sin orientación',
      'Quiz o formulario progresivo de preferencias',
      'Proceso de búsqueda, visita, negociación y cierre',
      'Experiencia local y señales de confianza reales',
      'CTA final para recibir propiedades compatibles',
    ],
    formFields: 'objetivo de compra, zonas, tipo de propiedad, presupuesto, recámaras, plazo y financiamiento opcional',
  },
  {
    id: 'open-house',
    number: '04',
    title: 'Open House',
    description: 'Registra interesados y organiza la asistencia a una visita especial.',
    objective: 'Registrar asistentes calificados para un open house específico.',
    cta: 'Reservar asistencia',
    detailLabel: 'Datos del Open House',
    detailPlaceholder: 'Ej. Sábado 18 de octubre, 11:00–15:00, residencia de 4 recámaras en Cumbres de Juárez…',
    detailHint: 'Incluye fecha, horario, propiedad, cupo y ubicación únicamente si puedes publicarla.',
    journey: 'Invitación → datos esenciales del evento → razones para visitar → confianza → reservación → confirmación.',
    sections: [
      'Hero tipo invitación con fecha, horario y CTA de reservación',
      'Galería y atributos principales de la propiedad',
      'Qué podrá conocer o resolver el visitante durante el evento',
      'Ubicación o instrucciones de llegada según la información permitida',
      'Formulario RSVP corto con selección de horario si aplica',
      'Confirmación preparada para calendario y canal de contacto',
    ],
    formFields: 'nombre, teléfono o correo, número de asistentes y horario preferido',
  },
  {
    id: 'development-presale',
    number: '05',
    title: 'Desarrollo / Preventa',
    description: 'Comunica el valor de un desarrollo y genera solicitudes calificadas.',
    objective: 'Presentar un desarrollo y convertir interés en solicitudes de disponibilidad o brochure.',
    cta: 'Solicitar disponibilidad',
    detailLabel: 'Describe el desarrollo',
    detailPlaceholder: 'Ej. 48 departamentos en Playas de Tijuana, modelos de 1 a 3 recámaras, rooftop y entrega estimada…',
    detailHint: 'Incluye concepto, tipologías, amenidades, etapa, fecha y precios solo cuando sean datos confirmados.',
    journey: 'Descubrimiento → visión del proyecto → producto y ubicación → confianza → disponibilidad → conversación comercial.',
    sections: [
      'Hero aspiracional con nombre del desarrollo y propuesta verificable',
      'Concepto arquitectónico y estilo de vida',
      'Tipologías, amenidades y master plan con datos reales',
      'Ubicación y conectividad sin inventar tiempos ni distancias',
      'Avance, proceso de compra y preguntas frecuentes',
      'Formulario para disponibilidad, brochure o cita',
    ],
    formFields: 'nombre, contacto, tipología de interés, presupuesto y plazo de compra opcional',
  },
  {
    id: 'agency-advisor',
    number: '06',
    title: 'Inmobiliaria / Asesor',
    description: 'Construye presencia de marca y abre una conversación con prospectos.',
    objective: 'Posicionar la experiencia de la marca y abrir conversaciones con prospectos relevantes.',
    cta: 'Hablar con un asesor',
    detailLabel: 'Describe tus servicios principales',
    detailPlaceholder: 'Ej. Compra, venta e inversión residencial en Tijuana con acompañamiento legal y financiero…',
    detailHint: 'Explica qué operaciones atiendes, en qué zonas y cómo es tu forma de trabajar.',
    journey: 'Primera impresión → elección de necesidad → experiencia local → proceso → evidencia → conversación.',
    sections: [
      'Hero de posicionamiento con CTA a conversación',
      'Selector claro para comprar, vender o invertir según los servicios reales',
      'Áreas de especialidad y cobertura geográfica',
      'Proceso de acompañamiento y forma de trabajo',
      'Perfil del asesor o equipo y evidencia real',
      'FAQ y CTA final de consulta',
    ],
    formFields: 'nombre, medio de contacto, operación de interés, zona y mensaje breve',
  },
];

export const guidedOptions = {
  'featured-property': {
    audience: [
      { id: 'first-home', label: 'Primera vivienda', text: 'personas y parejas que buscan comprar su primera vivienda y necesitan claridad para tomar una decisión' },
      { id: 'growing-family', label: 'Familias en crecimiento', text: 'familias que necesitan más espacio, una distribución práctica y una zona conveniente para su vida diaria' },
      { id: 'mortgage-buyers', label: 'Compradores con crédito', text: 'compradores que planean usar crédito hipotecario y valoran un proceso claro y bien acompañado' },
      { id: 'local-move', label: 'Cambio de zona', text: 'personas que ya viven en la ciudad y quieren mudarse a una zona que encaje mejor con su estilo de vida' },
      { id: 'investors', label: 'Inversionistas', text: 'inversionistas que comparan ubicación, demanda y potencial de renta antes de solicitar una visita' },
      { id: 'ready-to-visit', label: 'Listos para visitar', text: 'compradores activos que ya definieron sus prioridades y quieren conocer propiedades en el corto plazo' },
    ],
    offer: [
      { id: 'family-home', label: 'Casa familiar', text: 'Presentar una casa residencial desde la experiencia cotidiana: distribución, espacios para convivir, privacidad y ventajas comprobables de la zona. Usar únicamente características confirmadas.' },
      { id: 'urban-apartment', label: 'Departamento urbano', text: 'Presentar un departamento para una vida urbana práctica, priorizando distribución, conectividad, amenidades confirmadas y facilidad de mantenimiento sin inventar distancias.' },
      { id: 'premium-residence', label: 'Residencia premium', text: 'Presentar una residencia de alto valor mediante arquitectura, materiales, privacidad y experiencia espacial. La comunicación debe ser sobria y respaldar cada atributo con información real.' },
      { id: 'investment-property', label: 'Propiedad para inversión', text: 'Presentar una propiedad para compradores que evalúan inversión, destacando ubicación, configuración y demanda potencial sin prometer rendimientos ni plusvalía.' },
    ],
    specialty: [
      { id: 'residential-sales', label: 'Venta residencial', text: 'Venta y promoción de vivienda residencial' },
      { id: 'premium-market', label: 'Mercado premium', text: 'Comercialización de residencias y propiedades premium' },
      { id: 'investment', label: 'Inversión', text: 'Propiedades residenciales para inversión y generación de patrimonio' },
      { id: 'relocation', label: 'Relocalización', text: 'Acompañamiento a compradores que se mudan desde otra ciudad o país' },
    ],
  },
  'sell-property': {
    audience: [
      { id: 'know-value', label: 'Quieren conocer el valor', text: 'propietarios que quieren entender el valor comercial de su inmueble antes de decidir si venden' },
      { id: 'sell-soon', label: 'Necesitan vender pronto', text: 'propietarios que necesitan vender en un plazo definido y buscan una estrategia realista' },
      { id: 'move-home', label: 'Cambiarán de vivienda', text: 'familias que venderán su propiedad actual para comprar una vivienda que responda a una nueva etapa' },
      { id: 'inherited-property', label: 'Herencia o copropiedad', text: 'personas que necesitan ordenar la venta de una propiedad heredada o compartida con acompañamiento claro' },
      { id: 'empty-property', label: 'Propiedad desocupada', text: 'propietarios de inmuebles vacíos que quieren reducir tiempo, costo y complejidad de la venta' },
      { id: 'portfolio-owner', label: 'Dueños inversionistas', text: 'inversionistas que evalúan vender uno o varios activos y necesitan información de mercado confiable' },
    ],
    offer: [
      { id: 'strategic-valuation', label: 'Valoración estratégica', text: 'Ayudo a definir un precio de salida realista mediante análisis comparativo del mercado local, revisión del inmueble y una recomendación explicada con claridad.' },
      { id: 'end-to-end-sale', label: 'Venta de principio a fin', text: 'Acompaño la preparación del inmueble, publicación, filtrado de compradores, negociación y coordinación del cierre para que el propietario tenga claridad en cada etapa.' },
      { id: 'premium-marketing', label: 'Promoción de alto nivel', text: 'Desarrollo una presentación comercial cuidada con fotografía, narrativa, distribución selectiva y seguimiento a interesados calificados, usando únicamente recursos que realmente estén disponibles.' },
      { id: 'safe-operation', label: 'Operación segura', text: 'Organizo la venta con atención documental, comunicación constante y coordinación con especialistas legales o financieros cuando la operación lo requiere.' },
    ],
    specialty: [
      { id: 'seller-representation', label: 'Representación de vendedores', text: 'Captación, valoración y venta de propiedades residenciales' },
      { id: 'premium-listings', label: 'Propiedades premium', text: 'Venta estratégica de residencias y propiedades de alto valor' },
      { id: 'complex-sales', label: 'Operaciones complejas', text: 'Venta de propiedades heredadas, compartidas o con necesidades documentales especiales' },
      { id: 'investor-portfolio', label: 'Portafolios de inversión', text: 'Comercialización de propiedades para inversionistas y propietarios de múltiples activos' },
    ],
  },
  'find-property': {
    audience: [
      { id: 'first-home', label: 'Primera vivienda', text: 'personas y parejas que comprarán su primera vivienda y necesitan orientación sobre opciones, crédito y proceso' },
      { id: 'growing-family', label: 'Familias', text: 'familias que buscan más espacio y quieren comparar zonas, distribución y servicios cercanos' },
      { id: 'investors', label: 'Inversionistas', text: 'inversionistas que buscan propiedades compatibles con una estrategia patrimonial definida' },
      { id: 'relocation', label: 'Se mudan a la ciudad', text: 'personas que se mudan desde otra ciudad o país y necesitan contexto local antes de elegir una zona' },
      { id: 'second-home', label: 'Segunda vivienda', text: 'compradores que buscan una segunda residencia para uso personal, descanso o temporadas' },
      { id: 'ready-buyers', label: 'Compra en corto plazo', text: 'compradores activos con prioridades definidas que quieren visitar opciones relevantes pronto' },
    ],
    offer: [
      { id: 'first-home-search', label: 'Primera vivienda', text: 'Guiar una búsqueda de primera vivienda con opciones filtradas por presupuesto, zona, forma de pago y necesidades cotidianas, explicando el proceso sin presionar la decisión.' },
      { id: 'family-search', label: 'Mudanza familiar', text: 'Encontrar una vivienda para una nueva etapa familiar, comparando espacio, distribución, zonas y servicios importantes según las prioridades reales del comprador.' },
      { id: 'investment-search', label: 'Búsqueda para inversión', text: 'Buscar propiedades compatibles con una estrategia de inversión definida, comparando datos verificables y evitando promesas de rentabilidad o plusvalía.' },
      { id: 'relocation-search', label: 'Relocalización', text: 'Acompañar a una persona que llega a la ciudad con contexto de zonas, selección remota, recorridos organizados y apoyo durante la operación.' },
    ],
    specialty: [
      { id: 'buyer-advisory', label: 'Asesoría a compradores', text: 'Representación y acompañamiento de compradores de vivienda' },
      { id: 'mortgage-home', label: 'Primera vivienda y crédito', text: 'Primera vivienda y operaciones con crédito hipotecario' },
      { id: 'investment', label: 'Inversión inmobiliaria', text: 'Búsqueda y análisis de propiedades para inversión patrimonial' },
      { id: 'relocation', label: 'Relocalización', text: 'Búsqueda de vivienda para personas que llegan desde otra ciudad o país' },
    ],
  },
  'open-house': {
    audience: [
      { id: 'active-buyers', label: 'Compradores activos', text: 'compradores activos que quieren conocer la propiedad y resolver dudas en una visita organizada' },
      { id: 'first-home', label: 'Primera vivienda', text: 'personas que exploran su primera compra y quieren entender la propiedad y el proceso sin presión' },
      { id: 'families', label: 'Familias', text: 'familias que quieren evaluar distribución, espacios cotidianos y compatibilidad con su nueva etapa' },
      { id: 'investors', label: 'Inversionistas', text: 'inversionistas que desean revisar físicamente el inmueble y contrastar sus características reales' },
      { id: 'local-referrals', label: 'Vecinos y referidos', text: 'personas de la zona y contactos referidos que pueden estar interesados o conocer a un comprador compatible' },
      { id: 'qualified-buyers', label: 'Compradores precalificados', text: 'compradores con presupuesto o financiamiento definido que están listos para avanzar si la propiedad encaja' },
    ],
    offer: [
      { id: 'open-visit', label: 'Visita abierta', text: 'Organizar una visita abierta con horario definido, información esencial de la propiedad y registro breve para anticipar la asistencia.' },
      { id: 'scheduled-tours', label: 'Recorridos por horario', text: 'Organizar recorridos en horarios seleccionables para ofrecer atención personal, evitar saturación y confirmar a cada visitante.' },
      { id: 'launch-event', label: 'Evento de lanzamiento', text: 'Presentar una propiedad recién incorporada al mercado mediante una experiencia de lanzamiento enfocada en conocer espacios, resolver dudas y registrar interés real.' },
      { id: 'private-preview', label: 'Preview privado', text: 'Crear una invitación sobria para un recorrido privado con cupo controlado, confirmación individual y seguimiento posterior.' },
    ],
    specialty: [
      { id: 'residential-marketing', label: 'Marketing residencial', text: 'Promoción y venta de propiedades residenciales' },
      { id: 'property-events', label: 'Eventos inmobiliarios', text: 'Open houses, recorridos privados y eventos de lanzamiento' },
      { id: 'premium-market', label: 'Mercado premium', text: 'Presentaciones privadas para propiedades de alto valor' },
      { id: 'new-developments', label: 'Nuevos desarrollos', text: 'Eventos de presentación para desarrollos y propiedades nuevas' },
    ],
  },
  'development-presale': {
    audience: [
      { id: 'end-users', label: 'Quieren vivir ahí', text: 'compradores que buscan habitar el desarrollo y comparan distribución, estilo de vida, ubicación y proceso de compra' },
      { id: 'first-home', label: 'Primera vivienda', text: 'personas que consideran su primera vivienda y necesitan entender tipologías, etapas, pagos y acompañamiento' },
      { id: 'investors', label: 'Inversionistas', text: 'inversionistas que comparan producto, etapa, demanda potencial y condiciones verificables de compra' },
      { id: 'second-home', label: 'Segunda vivienda', text: 'compradores que buscan una segunda residencia para uso personal o temporadas' },
      { id: 'presale-buyers', label: 'Compradores de preventa', text: 'personas familiarizadas con preventas que quieren revisar avance, fechas, contrato y disponibilidad real' },
      { id: 'relocation', label: 'Se mudan a la zona', text: 'personas que planean mudarse a la zona y necesitan comprender el proyecto y su contexto antes de visitar' },
    ],
    offer: [
      { id: 'new-launch', label: 'Nuevo lanzamiento', text: 'Presentar el concepto de un desarrollo recién lanzado, sus tipologías, ubicación, amenidades confirmadas y proceso para solicitar información o disponibilidad.' },
      { id: 'presale', label: 'Preventa', text: 'Explicar una oportunidad de preventa con claridad sobre etapa, tipologías, esquema de compra y fechas confirmadas, sin inventar disponibilidad ni retorno.' },
      { id: 'near-delivery', label: 'Entrega próxima', text: 'Presentar un desarrollo cercano a entrega priorizando avance verificable, unidades disponibles, experiencia de los espacios y pasos para agendar una visita.' },
      { id: 'investment-focus', label: 'Enfoque de inversión', text: 'Presentar el desarrollo a compradores patrimoniales mediante datos verificables de producto, zona, demanda y condiciones de compra, sin prometer plusvalía.' },
    ],
    specialty: [
      { id: 'presales', label: 'Preventas', text: 'Comercialización y acompañamiento de compradores en preventas inmobiliarias' },
      { id: 'vertical', label: 'Desarrollo vertical', text: 'Departamentos, condominios y desarrollos residenciales verticales' },
      { id: 'horizontal', label: 'Comunidades residenciales', text: 'Fraccionamientos y desarrollos residenciales horizontales' },
      { id: 'investment', label: 'Producto de inversión', text: 'Desarrollos dirigidos a compradores patrimoniales e inversionistas' },
    ],
  },
  'agency-advisor': {
    audience: [
      { id: 'buyers', label: 'Compradores', text: 'personas que quieren comprar una propiedad con orientación local y acompañamiento durante la operación' },
      { id: 'sellers', label: 'Propietarios vendedores', text: 'propietarios que necesitan valorar, preparar y vender su inmueble con una estrategia clara' },
      { id: 'investors', label: 'Inversionistas', text: 'inversionistas que buscan criterio local y oportunidades compatibles con sus objetivos patrimoniales' },
      { id: 'relocation', label: 'Personas que se mudan', text: 'personas y familias que llegan desde otra ciudad o país y necesitan contexto para elegir dónde vivir' },
      { id: 'premium-clients', label: 'Clientes premium', text: 'compradores y propietarios de alto valor que esperan discreción, criterio y atención personal' },
      { id: 'developers', label: 'Desarrolladores', text: 'desarrolladores que necesitan estrategia comercial, posicionamiento y generación de demanda calificada' },
    ],
    offer: [
      { id: 'buy-sell', label: 'Compra y venta', text: 'Acompañar operaciones de compra y venta residencial con orientación clara, conocimiento local y coordinación de cada etapa hasta el cierre.' },
      { id: 'buyer-focus', label: 'Asesoría para compradores', text: 'Representar a compradores mediante diagnóstico de necesidades, selección de propiedades, recorridos, negociación y acompañamiento documental.' },
      { id: 'seller-focus', label: 'Estrategia para vendedores', text: 'Ayudar a propietarios a valorar, preparar, presentar y vender su propiedad con seguimiento transparente y filtrado de interesados.' },
      { id: 'investment-focus', label: 'Inversión inmobiliaria', text: 'Orientar decisiones patrimoniales con búsqueda, comparación y análisis de información verificable, sin prometer resultados financieros.' },
    ],
    specialty: [
      { id: 'residential', label: 'Residencial', text: 'Compra y venta de propiedades residenciales' },
      { id: 'premium', label: 'Residencial premium', text: 'Residencias y propiedades de alto valor' },
      { id: 'investment', label: 'Inversión', text: 'Asesoría para inversión y construcción de patrimonio inmobiliario' },
      { id: 'relocation', label: 'Relocalización', text: 'Acompañamiento inmobiliario para personas que se mudan a la ciudad' },
      { id: 'commercial', label: 'Comercial', text: 'Compra, venta y renta de propiedades comerciales' },
    ],
  },
};

export const differentiatorOptions = [
  { id: 'full-guidance', label: 'Acompañamiento integral', text: 'Acompañamiento personal desde la primera conversación hasta la firma, coordinando cada etapa y explicando las decisiones con claridad.' },
  { id: 'local-knowledge', label: 'Conocimiento local', text: 'Conocimiento profundo de la zona, sus rangos de mercado y la forma en que se desarrollan las operaciones locales.' },
  { id: 'fast-response', label: 'Respuesta ágil', text: 'Atención directa, seguimiento ágil y comunicación clara durante todo el proceso.' },
  { id: 'tailored-strategy', label: 'Estrategia a medida', text: 'Una estrategia personalizada según el objetivo, plazo y situación de cada cliente, en lugar de un proceso genérico.' },
  { id: 'specialist-network', label: 'Red de especialistas', text: 'Coordinación con aliados legales, financieros y técnicos cuando la operación lo requiere.' },
];

export const trustOptions = [
  { id: 'verified-reviews', label: 'Reseñas verificables', text: 'Reseñas verificables de clientes anteriores que pueden compartirse con autorización.' },
  { id: 'local-track-record', label: 'Experiencia en la zona', text: 'Trayectoria comprobable trabajando en este mercado y zona.' },
  { id: 'certifications', label: 'Certificaciones vigentes', text: 'Certificaciones o afiliaciones profesionales vigentes que pueden mostrarse.' },
  { id: 'documented-cases', label: 'Casos documentados', text: 'Casos de éxito documentados y autorizados para publicación.' },
  { id: 'specialist-team', label: 'Equipo de especialistas', text: 'Red verificable de aliados legales, financieros o técnicos.' },
  { id: 'real-portfolio', label: 'Portafolio real', text: 'Portafolio de operaciones o propiedades reales que puede mostrarse.' },
];

export const toneOptions = [
  { id: 'warm', value: 'Cálido y cercano', label: 'Cálido y cercano', description: 'Humano, claro y sin presión.', sample: 'Encuentra un lugar que sí se sienta tuyo.', accent: '#B85C43', soft: '#FFF0EA' },
  { id: 'premium', value: 'Premium y sobrio', label: 'Premium y sobrio', description: 'Elegante, sereno y preciso.', sample: 'Una residencia definida por sus espacios.', accent: '#8A6B3D', soft: '#F7F1E6' },
  { id: 'modern', value: 'Moderno y directo', label: 'Moderno y directo', description: 'Ágil, seguro y orientado a actuar.', sample: 'Conoce disponibilidad y agenda tu visita.', accent: '#C85732', soft: '#FFF0E8' },
  { id: 'expert', value: 'Experto y confiable', label: 'Experto y confiable', description: 'Didáctico, transparente y firme.', sample: 'Toma una decisión con información clara.', accent: '#356A73', soft: '#EAF5F6' },
  { id: 'minimal', value: 'Minimalista', label: 'Minimalista', description: 'Breve, visual y sin adornos.', sample: 'Espacio, ubicación y una visita.', accent: '#4D5A57', soft: '#EEF1F0' },
];

export const channelOptions = [
  { id: 'whatsapp', value: 'WhatsApp', label: 'WhatsApp', description: 'Conversación rápida desde el teléfono.', accent: '#187A61', soft: '#E9F7F2' },
  { id: 'form', value: 'Formulario de contacto', label: 'Formulario', description: 'Captura datos y necesidades del prospecto.', accent: '#4169A5', soft: '#EDF3FC' },
  { id: 'calendar', value: 'Agenda de citas', label: 'Agenda de citas', description: 'Permite elegir un horario disponible.', accent: '#7655A5', soft: '#F3EEFA' },
  { id: 'phone', value: 'Llamada telefónica', label: 'Llamada', description: 'Contacto directo con un asesor.', accent: '#B75948', soft: '#FFF0ED' },
];

export const visualStyles = [
  {
    id: 'editorial-luxury',
    title: 'Editorial de lujo',
    description: 'Sofisticado, fotográfico y sereno.',
    idealFor: 'Residencias premium',
    swatches: ['#171714', '#F3EFE6', '#9B805B'],
    direction: 'Usa una serif editorial de alto contraste para titulares y una sans neutral para lectura. Paleta marfil, tinta y un acento metálico mate; nunca dorado brillante. Composición asimétrica con fotografía de gran formato, mucho espacio negativo, líneas finas y detalles discretos. Radios bajos y sombras casi imperceptibles. Movimiento lento y elegante mediante fades y desplazamientos cortos.',
    avoid: 'Evita lujo recargado, fondos negros en todas las secciones, carruseles automáticos y tarjetas flotantes genéricas.',
  },
  {
    id: 'architectural-minimal',
    title: 'Arquitectónico',
    description: 'Preciso, limpio y contemporáneo.',
    idealFor: 'Desarrollos y preventas',
    swatches: ['#F7F7F2', '#171A1A', '#70837D'],
    direction: 'Trabaja con una retícula editorial rigurosa, sans geométrica, blanco cálido, grafito y un solo acento apagado. Usa mucho espacio negativo, divisores finos, alineaciones precisas y módulos técnicos para planos, amenidades y especificaciones. Geometría recta o radios de máximo 8px. La fotografía arquitectónica debe dominar y el movimiento debe ser sobrio y funcional.',
    avoid: 'Evita filas repetitivas de cards, exceso de pills, degradados decorativos y elementos sin una alineación clara.',
  },
  {
    id: 'warm-organic',
    title: 'Cálido orgánico',
    description: 'Humano, familiar y acogedor.',
    idealFor: 'Familias y primera vivienda',
    swatches: ['#F6F0E6', '#365348', '#C77C5D'],
    direction: 'Combina una sans humanista con una serif suave solo como acento. Usa crema, arena, verde oliva y terracota moderada. Fotografía con luz natural y personas reales cuando existan recursos. Formas suaves, radios de 16 a 22px, sombras cálidas muy tenues y composición cercana. Prioriza claridad, legibilidad y una sensación de acompañamiento personal.',
    avoid: 'Evita ilustraciones infantiles, ondas decorativas repetidas, tonos pastel sin contraste y exceso de elementos redondeados.',
  },
  {
    id: 'urban-bold',
    title: 'Urbano audaz',
    description: 'Gráfico, directo y memorable.',
    idealFor: 'Lofts e inversión',
    swatches: ['#202322', '#E7E3DB', '#D9663D'],
    direction: 'Usa tipografía sans de gran escala, alto contraste entre carbón, concreto y un color acento enérgico. Crea layouts divididos, recortes fotográficos decididos y una retícula modular para datos. Geometría marcada, bordes visibles y microinteracciones rápidas. El hero debe tener una decisión compositiva distintiva sin sacrificar la lectura.',
    avoid: 'Evita estética cyberpunk, neón, ruido visual, texto sobre imágenes sin contraste y animaciones continuas.',
  },
  {
    id: 'coastal-light',
    title: 'Costero luminoso',
    description: 'Aireado, natural y aspiracional.',
    idealFor: 'Propiedades vacacionales',
    swatches: ['#FBFAF6', '#184653', '#CBB995'],
    direction: 'Usa una serif editorial relajada con sans limpia. Paleta de blanco cálido, arena, azul profundo y tonos minerales. Ritmo amplio, imágenes horizontales de borde a borde y bloques de contenido con respiración generosa. Añade detalles orgánicos muy sutiles y transiciones suaves inspiradas en luz y amplitud, sin convertir el concepto en un tema literal.',
    avoid: 'Evita íconos de playa, olas decorativas obvias, turquesa saturado y clichés náuticos.',
  },
  {
    id: 'trusted-professional',
    title: 'Confianza profesional',
    description: 'Claro, experto y estructurado.',
    idealFor: 'Asesores y vendedores',
    swatches: ['#F5F7F6', '#193B43', '#4F716B'],
    direction: 'Usa una sans contemporánea con jerarquía firme, azul profundo, slate, blanco y un acento de marca. Retícula estructurada, radios moderados de 10 a 14px y componentes consistentes. Da protagonismo al proceso, alcance, experiencia local y evidencia real. La composición debe sentirse humana y editorial, no como software corporativo.',
    avoid: 'Evita bancos de íconos genéricos, estadísticas inventadas, bloques demasiado densos y estética de dashboard.',
  },
];

export const tones = toneOptions.map((option) => option.value);
export const channels = channelOptions.map((option) => option.value);
export const styleIntensities = ['Sutil', 'Equilibrada', 'Expresiva'];

export const emptyDraft = {
  websiteType: '',
  company: '',
  location: '',
  specialty: '',
  audience: '',
  audienceSelections: [],
  offerDetails: '',
  offerPreset: '',
  difference: '',
  differencePreset: '',
  trustProof: '',
  trustSelections: [],
  specialtyPreset: '',
  tone: tones[0],
  contactChannel: channels[0],
  businessWhatsapp: '',
  businessPhone: '',
  businessEmail: '',
  bookingUrl: '',
  visualStyle: visualStyles[1].id,
  styleIntensity: styleIntensities[1],
  brandColor: '',
  contactName: '',
  email: '',
  whatsapp: '',
  contactConsent: false,
  whatsappConsent: false,
  starterPackRequested: false,
};
